//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Needines
    {
        public int Needines_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Job { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Pic { get; set; }
        public string Income { get; set; }
        public Nullable<int> Education { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    }
}
